### ISSUE TITLE
no modules found !

### ISSUE THREAD

**Issue by ghost** [ArtskydJ/reverse-md5#9]
Could not find a declaration file for module 'reverse-md5'. 'c:/github/express-js-admin-panel-mysql/node_modules/reverse-md5/index.js'

**Comment by ArtskydJ** [comment]
Could you provide the code that you're running, or the command that you're running?

I saw your [repository](https://github.com/alialroomi/express-js-admin-panel-mysql/search?q=reverse-md5&unscoped_q=reverse-md5) but it looks like `reverse-md5` is only used in the package.json.

**Comment by ghost** [comment]
thanks a lot i just fix the error , but unfortunately i removed it at the
end because of logn time execution !,
however many thanks for your effort :)

**Comment by ArtskydJ** [comment]
:) yeah it's terrible performance. I was surprised anyone was trying to use it haha.
